### ISSUE TITLE
current index private olabilir

### ISSUE THREAD

**Issue by cagdaspektas** [VBT-FlutterCamp/Ruchan_Adiguzel_Covid-Splash-#1]
https://github.com/VBT-FlutterCamp/Ruchan_Adiguzel_Covid-Splash-/blob/f8b02c622eb00134efc869986a5986e1953835d0/covid_app/lib/Views/on_board_view.dart#L21

_currentindex daha hoş olur

**Comment by ruchan-o7** [comment]
Private'a çevirildi. 👍
