### ISSUE TITLE
elle verilen sayılar

### ISSUE THREAD

**Issue by cagdaspektas** [VBT-FlutterCamp/Ruchan_Adiguzel_Covid-Splash-#2]
https://github.com/VBT-FlutterCamp/Ruchan_Adiguzel_Covid-Splash-/blob/f8b02c622eb00134efc869986a5986e1953835d0/covid_app/lib/Views/on_board_view.dart#L24

elle verilen sayılar current index gibi yukarda priv bir şekilde verilebilir

**Comment by ruchan-o7** [comment]
Sayılar enum aracılığıyla verildi
