### ISSUE TITLE
production kodda yorum satırı olmamalı

### ISSUE THREAD

**Issue by cagdaspektas** [VBT-FlutterCamp/Ruchan_Adiguzel_Covid-Splash-#3]
https://github.com/VBT-FlutterCamp/Ruchan_Adiguzel_Covid-Splash-/blob/f8b02c622eb00134efc869986a5986e1953835d0/covid_app/lib/Views/on_board_view.dart#L34

**Comment by ruchan-o7** [comment]
Halledildi
